security:
    erase_credentials: false
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        our_db_provider:
            entity:
                class: App\Entity\User
                # property: username
    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        main:
            #pattern:    ^/
            provider: our_db_provider
            webauthn: 
                authentication:
                    routes:
                        options_path: /login/webauthn/options
                        result_path: /login/webauthn
                registration:
                    enabled: true
            form_login:
                login_path: login
                check_path: login
                default_target_path: /dashboard
            logout:
                path:   /logout
                target: dashboard.redirect
            remember_me:
                secret:   '%kernel.secret%'
            lazy:   true
    
    role_hierarchy:
        ROLE_RESERVATIONS: ROLE_RESERVATIONS_RO
        ROLE_ADMIN:
            - ROLE_RESERVATIONS
            - ROLE_CUSTOMERS
            - ROLE_INVOICES
            - ROLE_REGISTRATIONBOOK
            - ROLE_STATISTICS
            - ROLE_CASHJOURNAL
            - ROLE_HOUSEKEEPING

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/reset-password, roles: PUBLIC_ACCESS }
        - { path: ^/register,  roles: PUBLIC_ACCESS}
        - { path: ^/apartments/calendar, roles: PUBLIC_ACCESS }
        - { path: ^/reservation/*, roles: [ROLE_RESERVATIONS_RO, ROLE_RESERVATIONS] }
        - { path: ^/correspondence, roles: [ROLE_RESERVATIONS, ROLE_HOUSEKEEPING] }
        - { path: ^/operations/housekeeping, roles: ROLE_HOUSEKEEPING }
        - { path: ^/operations/frontdesk, roles: ROLE_HOUSEKEEPING }
        - { path: ^/operations/reports, roles: ROLE_HOUSEKEEPING }
        - { path: ^/customers, roles: ROLE_CUSTOMERS }
        - { path: ^/invoices, roles: ROLE_INVOICES }
        - { path: ^/registrationbook, roles: ROLE_REGISTRATIONBOOK }
        - { path: ^/statistics, roles: ROLE_STATISTICS }
        - { path: ^/cashjournal, roles: ROLE_CASHJOURNAL }
        - { path: ^/settings, roles: ROLE_ADMIN }
        - { path: ^/profile,  roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/logout, roles: IS_AUTHENTICATED }
        - { path: ^/dashboard, roles: IS_AUTHENTICATED }
        - { path: ^/, roles: IS_AUTHENTICATED }

when@test:
    security:
        password_hashers:
            # Password hashers are resource-intensive by design to ensure security.
            # In tests, it's safe to reduce their cost to improve performance.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon