twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['form/fewohbee_bootstrap_5_layout.html.twig']
    globals:
        passkey_enabled: '%passkey_enabled%'

when@test:
    twig:
        strict_variables: true
