<?php

declare(strict_types=1);

namespace App\Repository;

use App\Entity\Appartment;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\ORM\NoResultException;
use Doctrine\ORM\QueryBuilder;
use Doctrine\Persistence\ManagerRegistry;

/**
 * AppartmentRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppartmentRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Appartment::class);
    }

    private function createBaseQueryBuilder(): QueryBuilder
    {
        return $this->createQueryBuilder('a')
            ->leftJoin('a.object', 'o')
            ->addSelect('o');
    }

    private function addDefaultSorting(QueryBuilder $qb): QueryBuilder
    {
        return $qb
            ->addOrderBy('o.name', 'ASC')
            ->addOrderBy('LENGTH(a.number)', 'ASC')
            ->addOrderBy('a.number', 'ASC');
    }

    public function findAll(): array
    {
        return $this->addDefaultSorting($this->createBaseQueryBuilder())
            ->getQuery()
            ->getResult();
    }

    /**
     * Load all apartment IDs for configuration resolution in Online Booking.
     *
     * @return int[]
     */
    public function loadAllIds(): array
    {
        $rows = $this->createQueryBuilder('a')
            ->select('a.id')
            ->getQuery()
            ->getArrayResult();

        return array_map(static fn (array $row): int => (int) $row['id'], $rows);
    }

    /**
     * Return only existing apartment IDs from a given selection.
     *
     * @param int[] $ids
     * @return int[]
     */
    public function loadExistingIds(array $ids): array
    {
        if ([] === $ids) {
            return [];
        }

        $rows = $this->createQueryBuilder('a')
            ->select('a.id')
            ->where('a.id IN (:ids)')
            ->setParameter('ids', $ids)
            ->getQuery()
            ->getArrayResult();

        return array_map(static fn (array $row): int => (int) $row['id'], $rows);
    }

    public function loadSumBedsMinForObject($objectId)
    {
        if ('all' === $objectId) {
            $query = $this->createQueryBuilder('u')
            ->select('SUM(u.beds_max)')
            // ->addGroupBy('u.object')
            ->getQuery();
        } else {
            $query = $this->createQueryBuilder('u')
            ->select('SUM(u.beds_max)')
            ->where('u.object = :id')
            // ->addGroupBy('u.object')
            ->setParameter('id', $objectId)
            ->getQuery();
        }

        try {
            return $query->getSingleScalarResult();
        } catch (NoResultException $ex) {
            return 0;
        }
    }

    public function findAllByProperty($propertyId = 'all'): array
    {
        if ('all' === $propertyId) {
            return $this->findAll();
        }

        return $this->addDefaultSorting(
            $this->createBaseQueryBuilder()
                ->andWhere('a.object = :id')
                ->setParameter('id', $propertyId)
        )
            ->getQuery()
            ->getResult();
    }

    /**
     * Count apartments (rooms) for a specific subsidiary or across all.
     */
    public function loadRoomCountForObject($objectId): int
    {
        $qb = $this->createQueryBuilder('a')
            ->select('COUNT(a.id)');

        if ('all' !== $objectId) {
            $qb->andWhere('a.object = :id')
                ->setParameter('id', $objectId);
        }

        try {
            return (int) $qb->getQuery()->getSingleScalarResult();
        } catch (NoResultException $ex) {
            return 0;
        }
    }

    /**
     * Return rooms limited to the given room and subsidiary IDs with joins needed for public booking.
     *
     * @param int[] $roomIds
     * @param int[] $subsidiaryIds
     *
     * @return Appartment[]
     */
    public function findForPublicBooking(array $roomIds, array $subsidiaryIds): array
    {
        if ([] === $roomIds || [] === $subsidiaryIds) {
            return [];
        }

        return $this->createQueryBuilder('a')
            ->leftJoin('a.roomCategory', 'rc')
            ->addSelect('rc')
            ->join('a.object', 'o')
            ->addSelect('o')
            ->where('a.id IN (:roomIds)')
            ->andWhere('o.id IN (:subsidiaryIds)')
            ->setParameter('roomIds', $roomIds)
            ->setParameter('subsidiaryIds', $subsidiaryIds)
            ->addOrderBy('rc.name', 'ASC')
            ->addOrderBy('LENGTH(a.number)', 'ASC')
            ->addOrderBy('a.number', 'ASC')
            ->getQuery()
            ->getResult();
    }

    /**
     * Load rooms by IDs including category and subsidiary joins used during deterministic assignment.
     *
     * @param int[] $ids
     *
     * @return Appartment[]
     */
    public function findByIdsWithRelations(array $ids): array
    {
        if ([] === $ids) {
            return [];
        }

        return $this->createQueryBuilder('a')
            ->leftJoin('a.roomCategory', 'rc')
            ->addSelect('rc')
            ->join('a.object', 'o')
            ->addSelect('o')
            ->where('a.id IN (:ids)')
            ->setParameter('ids', $ids)
            ->getQuery()
            ->getResult();
    }
}
