<?php

declare(strict_types=1);

namespace App\Repository;

use App\Entity\Appartment;
use App\Entity\Reservation;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\ORM\NoResultException;
use Doctrine\ORM\QueryBuilder;
use Doctrine\Persistence\ManagerRegistry;

/**
 * AppartmentRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppartmentRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Appartment::class);
    }

    private function createBaseQueryBuilder(): QueryBuilder
    {
        return $this->createQueryBuilder('a')
            ->leftJoin('a.object', 'o')
            ->addSelect('o');
    }

    private function addDefaultSorting(QueryBuilder $qb): QueryBuilder
    {
        return $qb
            ->addOrderBy('o.name', 'ASC')
            ->addOrderBy('LENGTH(a.number)', 'ASC')
            ->addOrderBy('a.number', 'ASC');
    }

    public function findAll(): array
    {
        return $this->addDefaultSorting($this->createBaseQueryBuilder())
            ->getQuery()
            ->getResult();
    }

    public function loadSumBedsMinForObject($objectId)
    {
        if ('all' === $objectId) {
            $query = $this->createQueryBuilder('u')
            ->select('SUM(u.beds_max)')
            // ->addGroupBy('u.object')
            ->getQuery();
        } else {
            $query = $this->createQueryBuilder('u')
            ->select('SUM(u.beds_max)')
            ->where('u.object = :id')
            // ->addGroupBy('u.object')
            ->setParameter('id', $objectId)
            ->getQuery();
        }

        try {
            return $query->getSingleScalarResult();
        } catch (NoResultException $ex) {
            return 0;
        }
    }

    public function findAllByProperty($propertyId = 'all'): array
    {
        if ('all' === $propertyId) {
            return $this->findAll();
        }

        return $this->addDefaultSorting(
            $this->createBaseQueryBuilder()
                ->andWhere('a.object = :id')
                ->setParameter('id', $propertyId)
        )
            ->getQuery()
            ->getResult();
    }
}
