<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * PriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriceRepository extends EntityRepository
{
    public function getActiveAppartmentPrices()
    {
        $q = $this
            ->createQueryBuilder('p')
            ->select('p')
            ->where('p.type = 2 AND p.active = true')
            ->getQuery();

        $prices = null;
        try {
            $prices = $q->getResult();
        } catch (NoResultException $e) {

        }

        return $prices;
    }

    public function getActiveMiscellaneousPrices()
    {
        $q = $this
            ->createQueryBuilder('p')
            ->select('p')
            ->where('p.type = 1 AND p.active = true')
            ->getQuery();

        $prices = null;
        try {
            $prices = $q->getResult();
        } catch (NoResultException $e) {

        }

        return $prices;
    }

    public function supportsClass($class)
    {
        return $this->getEntityName() === $class
        || is_subclass_of($class, $this->getEntityName());
    }
}
