<?php

declare(strict_types=1);

namespace App\Repository;

use App\Entity\Appartment;
use App\Entity\CalendarSyncImport;
use App\Entity\Reservation;
use App\Entity\Subsidiary;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\DBAL\ArrayParameterType;
use Doctrine\ORM\NoResultException;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\Uid\Uuid;

/**
 * ReservationRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Reservation::class);
    }

    private function applyBlockingStatusFilter($qb, string $reservationAlias = 'u', string $mode = 'blocking', string $statusAlias = 'rs'): void
    {
        if ('all' === $mode) {
            return;
        }

        $qb->join($reservationAlias.'.reservationStatus', $statusAlias);
        if ('non_blocking' === $mode) {
            $qb->andWhere($statusAlias.'.isBlocking = 0');
        } else {
            $qb->andWhere($statusAlias.'.isBlocking = 1');
        }
    }

    private function applyReservationStatusFilter($qb, ?array $statusIds, string $reservationAlias = 'u', string $statusAlias = 'rs'): void
    {
        if (null === $statusIds) {
            return;
        }

        if (!$statusIds) {
            $this->applyBlockingStatusFilter($qb, $reservationAlias, 'blocking', $statusAlias);

            return;
        }

        $qb->join($reservationAlias.'.reservationStatus', $statusAlias)
            ->andWhere($statusAlias.'.id IN (:reservationStatus)')
            ->setParameter('reservationStatus', $statusIds, ArrayParameterType::INTEGER);
    }

    public function loadReservationsForPeriod($startDate, $endDate)
    {
        $start = date('Y-m-d', strtotime($startDate));
        $end = date('Y-m-d', strtotime($endDate));

        //        if($customer == null) {
        $qb = $this
            ->createQueryBuilder('u')
            ->select('u')
            ->andWhere('((u.startDate >= :start AND u.startDate < :end AND u.endDate > :start AND u.endDate <= :end) OR'
                .'(u.startDate <= :start AND u.endDate > :start AND u.endDate <= :end) OR'
                .'(u.startDate >= :start AND u.startDate < :end AND u.endDate > :end) OR'
                .'(u.startDate <= :start AND u.endDate >= :end))')
            // ->andWhere('u.invoice IS NULL')
            ->setParameter('start', $start)
            ->setParameter('end', $end)
            ->addOrderBy('u.endDate', 'ASC');
        $this->applyBlockingStatusFilter($qb, 'u');
        $q = $qb->getQuery();
        //        } else {
        //            $q = $this
        //                ->createQueryBuilder('u')
        //                ->select('u')
        //                ->andWhere('((u.startDate >= :start AND u.startDate < :end AND u.endDate > :start AND u.endDate <= :end) OR'
        //                         .  '(u.startDate <= :start AND u.endDate > :start AND u.endDate <= :end) OR'
        //                         .  '(u.startDate >= :start AND u.startDate < :end AND u.endDate > :end) OR'
        //                         .  '(u.startDate <= :start AND u.endDate >= :end))')
        //                ->andWhere('u.invoice IS NULL')
        //                ->andWhere('u.booker = :customer')
        //                ->setParameter('start', $start)
        //                ->setParameter('end', $end)
        //                ->setParameter('customer', $customer)
        //                ->addOrderBy('u.endDate', 'ASC')
        //                ->getQuery();
        //        }

        $reservations = null;
        try {
            $reservations = $q->getResult();
        } catch (NoResultException $e) {
        }

        return $reservations;
    }

    /**
     * Load reservations for housekeeping views with required joins and conflict filters.
     *
     * @return Reservation[]
     */
    public function findForHousekeepingRange(
        \DateTimeImmutable $start,
        \DateTimeImmutable $end,
        ?Subsidiary $subsidiary,
        string $statusMode = 'blocking'
    ): array {
        $qb = $this->createQueryBuilder('r')
            ->addSelect('a', 'booker', 'customer')
            ->leftJoin('r.appartment', 'a')
            ->leftJoin('r.booker', 'booker')
            ->leftJoin('r.customers', 'customer')
            ->distinct()
            ->andWhere('r.startDate < :end')
            ->andWhere('r.endDate >= :start')
            ->andWhere('r.isConflict = 0')
            ->andWhere('r.isConflictIgnored = 0')
            ->setParameter('start', $start)
            ->setParameter('end', $end)
            ->addOrderBy('r.startDate', 'ASC');

        if ($subsidiary instanceof Subsidiary) {
            $qb->andWhere('a.object = :subsidiary')
                ->setParameter('subsidiary', $subsidiary->getId());
        }

        $this->applyBlockingStatusFilter($qb, 'r', $statusMode);

        return $qb->getQuery()->getResult();
    }

    public function supportsClass($class)
    {
        return $this->getEntityName() === $class
        || is_subclass_of($class, $this->getEntityName());
    }

    /**
     * Loads reservations that overlap the period, including those that merely touch the boundaries
     * (e.g. endDate = start or startDate = end).
     */
    public function loadReservationsForApartment(\DateTimeInterface $start, \DateTimeInterface $end, Appartment $apartment, string $statusMode = 'blocking'): array
    {
        $qb = $this
            ->createQueryBuilder('u')
            ->select('u')
            ->where('u.appartment = :app ')
            ->andWhere('u.isConflict = 0')
            ->andWhere('u.startDate <= :end AND u.endDate >= :start')
            ->setParameter('start', $start)
            ->setParameter('end', $end)
            ->setParameter('app', $apartment->getId())
            ->addOrderBy('u.endDate', 'ASC');

        $this->applyBlockingStatusFilter($qb, 'u', $statusMode);

        $q = $qb->getQuery();

        $reservations = [];
        try {
            $reservations = $q->getResult();
        } catch (NoResultException $e) {
        }

        return $reservations;
    }

    /**
     * Loads reservations that truly overlap the period. Turnovers are excluded:
     * a reservation ending exactly at start or starting exactly at end is ignored.
     */
    public function loadReservationsForApartmentWithoutStartEnd(\DateTimeInterface $start, \DateTimeInterface $end, Appartment $apartment): array
    {
        $qb = $this
            ->createQueryBuilder('u')
            ->select('u')
            ->where('u.appartment = :app ')
            ->andWhere('u.isConflict = 0')
            ->andWhere('u.startDate < :end AND u.endDate > :start')
            ->setParameter('start', $start)
            ->setParameter('end', $end)
            ->setParameter('app', $apartment->getId())
            ->addOrderBy('u.endDate', 'ASC');

        $this->applyBlockingStatusFilter($qb, 'u');

        $q = $qb->getQuery();

        $reservations = [];
        try {
            $reservations = $q->getResult();
        } catch (NoResultException $e) {
        }

        return $reservations;
    }

    /**
     * Load aggregated blocking occupancy data for multiple apartments in a single query.
     * Turnovers are excluded (same logic as loadReservationsForApartmentWithoutStartEnd).
     *
     * @param int[] $apartmentIds
     * @return array<int, array{reservationCount: int, persons: int}>
     */
    public function loadOccupancyByApartmentIdsWithoutStartEnd(\DateTimeInterface $start, \DateTimeInterface $end, array $apartmentIds): array
    {
        if ([] === $apartmentIds) {
            return [];
        }

        $qb = $this
            ->createQueryBuilder('u')
            ->select('IDENTITY(u.appartment) AS appartmentId')
            ->addSelect('COUNT(u.id) AS reservationCount')
            ->addSelect('COALESCE(SUM(u.persons), 0) AS persons')
            ->where('u.appartment IN (:apps)')
            ->andWhere('u.isConflict = 0')
            ->andWhere('u.startDate < :end AND u.endDate > :start')
            ->setParameter('start', $start)
            ->setParameter('end', $end)
            ->setParameter('apps', $apartmentIds, ArrayParameterType::INTEGER)
            ->groupBy('u.appartment');

        $this->applyBlockingStatusFilter($qb, 'u');

        $rows = $qb->getQuery()->getArrayResult();
        $occupancy = [];

        foreach ($rows as $row) {
            $occupancy[(int) $row['appartmentId']] = [
                'reservationCount' => (int) $row['reservationCount'],
                'persons' => (int) $row['persons'],
            ];
        }

        return $occupancy;
    }

    /**
     * Load all reservations for multiple apartments in a single query.
     * Includes boundary touches (for table display where partial reservations must be shown).
     *
     * @param Appartment[] $apartments
     *
     * @return Reservation[]
     */
    public function loadReservationsForApartments(\DateTimeInterface $start, \DateTimeInterface $end, array $apartments, string $statusMode = 'blocking'): array
    {
        if ([] === $apartments) {
            return [];
        }

        $apartmentIds = array_map(fn ($a) => $a->getId(), $apartments);

        $qb = $this
            ->createQueryBuilder('u')
            ->select('u')
            ->addSelect('booker', 'calImport')
            ->leftJoin('u.booker', 'booker')
            ->leftJoin('booker.customerAddresses', 'addr')
            ->leftJoin('u.calendarSyncImport', 'calImport')
            ->where('u.appartment IN (:apps)')
            ->andWhere('u.isConflict = 0')
            ->andWhere('u.startDate <= :end AND u.endDate >= :start')
            ->setParameter('start', $start)
            ->setParameter('end', $end)
            ->setParameter('apps', $apartmentIds, ArrayParameterType::INTEGER)
            ->addOrderBy('u.startDate', 'ASC')
            ->addOrderBy('u.endDate', 'ASC');

        $this->applyBlockingStatusFilter($qb, 'u', $statusMode);

        return $qb->getQuery()->getResult();
    }

    public function loadReservationsWithoutInvoiceForCustomer(\App\Entity\Customer $customer)
    {
        $q = $this
            ->createQueryBuilder('u')
            ->select('u')
            ->where('u.booker = :booker')
            // ->andWhere('u.invoice IS NULL')
            ->setParameter('booker', $customer->getId())
            ->addOrderBy('u.endDate', 'ASC')
            ->getQuery();

        $reservations = null;
        try {
            $reservations = $q->getResult();
        } catch (NoResultException $e) {
        }

        return $reservations;
    }

    /**
     * @return Reservation[]
     */
    public function findByBookingGroupUuid(Uuid $bookingGroupUuid): array
    {
        return $this->createQueryBuilder('u')
            ->where('u.bookingGroupUuid = :bookingGroupUuid')
            ->setParameter('bookingGroupUuid', $bookingGroupUuid, 'uuid')
            ->orderBy('u.startDate', 'ASC')
            ->addOrderBy('u.id', 'ASC')
            ->getQuery()
            ->getResult();
    }

    public function loadUtilizationForDay($day, $objectId, array $reservationStatus = [])
    {
        if ('all' === $objectId) {
            $qb = $this->createQueryBuilder('u')
            ->select('SUM(u.persons)')
            ->where(':day >= u.startDate and (:day < u.endDate or (:day = u.startDate and u.startDate = u.endDate))')
            ->andWhere('u.isConflict = 0')
            ->andWhere('u.isConflictIgnored = 0')
            // ->andWhere('u.status=1')
            // ->addGroupBy('u.persons')
            ->setParameter('day', $day);
        } else {
            $qb = $this->createQueryBuilder('u')
            ->select('SUM(u.persons)')
            ->where('a.object = :objId and :day >= u.startDate and (:day < u.endDate or (:day = u.startDate and u.startDate = u.endDate))')
            ->andWhere('u.isConflict = 0')
            ->andWhere('u.isConflictIgnored = 0')
            // ->andWhere('u.status=1')
            ->join('u.appartment', 'a')
            // ->addGroupBy('u.persons')
            ->setParameter('day', $day)
            ->setParameter('objId', $objectId);
        }

        try {
            $this->applyReservationStatusFilter($qb, $reservationStatus, 'u');

            return $qb->getQuery()->getSingleScalarResult();
        } catch (NoResultException $ex) {
            return 0;
        }
    }

    public function getMinEndDate()
    {
        $q = $this
            ->createQueryBuilder('r')
            ->select('MIN(r.endDate)')
            ->getQuery();

        return $q->getSingleScalarResult();
    }

    public function getMaxStartDate()
    {
        $q = $this
            ->createQueryBuilder('r')
            ->select('MAX(r.startDate)')
            ->getQuery();

        return $q->getSingleScalarResult();
    }

    public function loadReservationsForMonth($month, $year, $objectId, ?array $reservationStatus = [])
    {
        $startTs = strtotime($year.'-'.$month.'-01');
        $start = date('Y-m-d', $startTs);
        $end = date('Y-m-d', strtotime('+1 month', $startTs));

        $qb = $this
            ->createQueryBuilder('u')
            ->select('u')
            ->join('u.appartment', 'a')
            // ->where('u.status=1')
            ->where('u.startDate < :end AND u.endDate > :start')
            ->andWhere('u.isConflict = 0')
            ->andWhere('u.isConflictIgnored = 0')
            ->setParameter('start', $start)
            ->setParameter('end', $end)
            ->addOrderBy('u.endDate', 'ASC');

        if ('all' !== $objectId) {
            $qb->andWhere('a.object = :objId')
              ->setParameter('objId', $objectId);
        }

        try {
            $this->applyReservationStatusFilter($qb, $reservationStatus, 'u');

            return $qb->getQuery()->getResult();
        } catch (NoResultException $e) {
            return [];
        }
    }

    public function loadOriginStatisticForPeriod($start, $end, $objectId, ?array $reservationStatus = [])
    {
        if ('all' === $objectId) {
            $qb = $this->createQueryBuilder('u')
            ->select('ro.id, COUNT(u.id) as origins')
            ->join('u.reservationOrigin', 'ro')
            ->where('u.startDate >= :start and u.endDate <= :end')
            ->andWhere('u.isConflict = 0')
            ->andWhere('u.isConflictIgnored = 0')
            // ->andWhere('u.status=1')
            ->addGroupBy('u.reservationOrigin')
            ->setParameter('start', $start)
            ->setParameter('end', $end);
        } else {
            $qb = $this->createQueryBuilder('u')
            ->select('ro.id, COUNT(u.id) as origins')
            ->join('u.reservationOrigin', 'ro')
            ->where('a.object = :objId and u.startDate >= :start and u.endDate <= :end')
            ->andWhere('u.isConflict = 0')
            ->andWhere('u.isConflictIgnored = 0')
            // ->andWhere('u.status=1')
            ->join('u.appartment', 'a')
            ->addGroupBy('u.reservationOrigin')
            ->setParameter('start', $start)
            ->setParameter('end', $end)
            ->setParameter('objId', $objectId);
        }

        try {
            $this->applyReservationStatusFilter($qb, $reservationStatus, 'u');

            return $qb->getQuery()->getArrayResult();
        } catch (NoResultException $ex) {
            return 0;
        }
    }

    /**
     * Load a reservation by import UID and source.
     */
    public function findOneByRefUidAndImport(string $refUid, CalendarSyncImport $import): ?Reservation
    {
        return $this->createQueryBuilder('u')
            ->where('u.refUid = :refUid')
            ->andWhere('u.calendarSyncImport = :import')
            ->setParameter('refUid', $refUid)
            ->setParameter('import', $import)
            ->getQuery()
            ->getOneOrNullResult();
    }

    /**
     * Return active conflict reservations that are not ignored.
     *
     * @return Reservation[]
     */
    public function findActiveConflicts(): array
    {
        return $this->createQueryBuilder('u')
            ->where('u.isConflict = 1')
            ->andWhere('u.isConflictIgnored = 0')
            ->orderBy('u.startDate', 'ASC')
            ->getQuery()
            ->getResult();
    }

    /**
     * Count active conflict reservations that are not ignored.
     */
    public function countActiveConflicts(): int
    {
        return (int) $this->createQueryBuilder('u')
            ->select('COUNT(u.id)')
            ->where('u.isConflict = 1')
            ->andWhere('u.isConflictIgnored = 0')
            ->getQuery()
            ->getSingleScalarResult();
    }

    /**
     * Count imported reservations without a booker that are not conflicts.
     */
    public function countImportedWithoutBooker(): int
    {
        return (int) $this->createQueryBuilder('u')
            ->select('COUNT(u.id)')
            ->where('u.calendarSyncImport IS NOT NULL')
            ->andWhere('u.booker IS NULL')
            ->andWhere('u.isConflict = 0')
            ->getQuery()
            ->getSingleScalarResult();
    }

    /**
     * Return imported reservations without a booker that are not conflicts.
     *
     * @return Reservation[]
     */
    public function findImportedWithoutBookerPaginated(int $page, int $perPage): array
    {
        $offset = max(0, ($page - 1) * $perPage);

        return $this->createQueryBuilder('u')
            ->where('u.calendarSyncImport IS NOT NULL')
            ->andWhere('u.booker IS NULL')
            ->andWhere('u.isConflict = 0')
            ->orderBy('u.startDate', 'ASC')
            ->setFirstResult($offset)
            ->setMaxResults($perPage)
            ->getQuery()
            ->getResult();
    }
}
