<?php

declare(strict_types=1);

namespace App\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * ReservationRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplateRepository extends EntityRepository
{
    public function findAll(): array
    {
        return $this->findBy([], ['name' => 'ASC']);
    }

    public function loadByTypeName($names)
    {
        $q = $this
            ->createQueryBuilder('t')
            ->select('t', 'tt')
            ->join('t.templateType', 'tt');
        // ->where('tt.name LIKE :name ')
        // ->setParameter('name', $name);
        // ->addOrderBy('u.endDate', 'ASC')
        // ->getQuery();

        $len = count($names);
        for ($i = 0; $i < $len; ++$i) {
            if (0 == $i) {
                $q->where('tt.name LIKE :name'.$i.' ');
            } else {
                $q->orWhere('tt.name LIKE :name'.$i.' ');
            }
            $q->setParameter('name'.$i, $names[$i]);
        }
        $q = $q->getQuery();

        $templates = null;
        try {
            $templates = $q->getResult();
        } catch (NoResultException $e) {
        }

        return $templates;
    }
}
